categories = [{"keyword": "project manager", "title": "Project Management"},
              {"keyword": "planning", "title": "Project Management"},
              {"keyword": "product manager", "title": "Product Management"},
              {"keyword": "product", "title": "Product Management"},
              {"keyword": "operations", "title": "Operations"},
              {"keyword": "partnership", "title": "Operations"},
              {"keyword": "manufacturing", "title": "Operations"},
              {"keyword": "logistics", "title": "Operations"},
              {"keyword": "office manager", "title": "Operations"},
              {"keyword": "director", "title": "Management"},
              {"keyword": "vp", "title": "Manager"},
              {"keyword": "team lead", "title": "Manager"},
              {"keyword": "manager", "title": "Manager"},
              {"keyword": "developer", "title": "Software Developer"},
              {"keyword": "aws", "title": "Software Developer"},
              {"keyword": "programmer", "title": "Software Developer"},
              {"keyword": "software engineer", "title": "Software Developer"},
              {"keyword": "devops", "title": "Software Developer"},
              {"keyword": "full stack", "title": "Software Developer"},
              {"keyword": "cloud", "title": "Software Developer"}, 
              {"keyword": "qa", "title": "Software Developer"},
              {"keyword": "marketing", "title": "Marketing"},
              {"keyword": "marketer", "title": "Marketing"},
              {"keyword": "demand generation", "title": "Marketing"},
              {"keyword": "content", "title": "Marketing"},
              {"keyword": "customer", "title": "Customer Experience"}, 
              {"keyword": "educator", "title": "Customer Experience"},
              {"keyword": "cx", "title": "Customer Experience"},
              {"keyword": "finance", "title": "Finance"},
              {"keyword": "accouting", "title": "Finance"},
              {"keyword": "accounts", "title": "Finance"},
              {"keyword": "it", "title": "IT Support"},
              {"keyword": "network", "title": "IT Support"},
              {"keyword": "system administrator", "title": "IT Support"},
              {"keyword": "computer support", "title": "IT Support"},
              {"keyword": "receptionist", "title": "Office Administration"},
              {"keyword": "office administator", "title": "Office Administration"},
              {"keyword": "executive assistant", "title": "Office Administration"},
              {"keyword": "consultant", "title": "Consulting"},
              {"keyword": "sap", "title": "Consulting"},
              {"keyword": "consulting", "title": "Consulting"},
              {"keyword": "mechanical engineer", "title": "Engineering"},
              {"keyword": "electrical engineer", "title": "Engineering"},
              {"keyword": "technologist", "title": "Engineering"},
              {"keyword": "fpga", "title": "Engineering"},
              {"keyword": "design", "title": "Design"},
              {"keyword": "ui", "title": "Design"},
              {"keyword": "ux", "title": "Design"},
              {"keyword": "designer", "title": "Design"},
              {"keyword": "artist", "title": "Design"},
              {"keyword": "animator", "title": "Design"},
              {"keyword": "data", "title": "Data"},
              {"keyword": "ai", "title": "Data"},
              {"keyword": "ml", "title": "Data"},
              {"keyword": "computational", "title": "Data"},
              {"keyword": "bioinformatician", "title": "Data"},
              {"keyword": "hr", "title": "HR"},
              {"keyword": "human recources", "title": "HR"},
              {"keyword": "people", "title": "HR"},
              {"keyword": "culture", "title": "HR"},
              {"keyword": "recruiter", "title": "HR"},
              {"keyword": "security", "title": "Cypersecurity"},
              {"keyword": "cybersecurity", "title": "Cypersecurity"},
              {"keyword": "internship", "title": "Intership"},
              {"keyword": "intern", "title": "Intership"},
              {"keyword": "student", "title": "Intership"},
              {"keyword": "co-op", "title": "Intership"},
              ]